import Head from "next/head";
import React from "react";
import { SiProgress } from "react-icons/si";
import { IoIosContact } from "react-icons/io";
import { GiHamburgerMenu } from "react-icons/gi";

const Contact = () => {
  return (
    <div>
      <Head>
        <title>Contact Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0'
        ></meta>
      </Head>
      <section className=''>
        <div className='form'>
          <form className='my-8 mx-8'>
            <div className='flex   '>
              <div className='w-[50%] hidden md:block rounded-2xl py-4 h-[31rem] bg-gradient-to-r from-cyan-500 to-blue-500'>
                <div className='flex text-center justify-center font-extrabold text-blue-50 text-3xl'>
                  <h1 className=' '>CODE OGRE </h1>
                  <SiProgress className='font-bold text-xl mt-2 mx-2' />
                </div>
                <div className='content text-white font-medium'>
                  <p className='text-center mx-10'>
                    feel lor free to ask me any thing
                  </p>
                  Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                  Exercitationem possimus culpa explicabo perspiciatis commodi,
                  necessitatibus ab aliquid dolore quaerat esse nihil atque
                  soluta officiis repudiandae incidunt, rem, nostrum totam et!
                </div>
              </div>
              <div className='contact lg:w-[50%] rounded-lg border-4  h-[31rem] bg-gray-300  '>
                <div className='heade  text-center justify-center items-center'>
                  <IoIosContact className='mx-auto my-2 text-6xl text-blue-700' />
                </div>
                <div className='inputs text-center space-y-8 my-5'>
                  <input
                    placeholder='Enter Your Name'
                    className='w-[70%] bg-slate-400 h-9 rounded-lg pl-3 placeholder:text-gray-700 placeholder:font-sans'
                    type='text'
                  />
                  <br />
                  <input
                    placeholder='Enter Your Email'
                    className='w-[70%] bg-slate-400 h-9 rounded-lg pl-3 placeholder:text-gray-700 placeholder:font-sans'
                    type='text'
                  />
                  <br />
                  <input
                    placeholder='Enter Your Subject'
                    className='w-[70%] bg-slate-400 h-9 rounded-lg pl-3 placeholder:text-gray-700 placeholder:font-sans'
                    type='text'
                  />
                  <br />
                  <textarea
                    placeholder='Enter Your Message'
                    className='bg-slate-400 px-3 mx-10 lg:mx-0 rounded-lg pt-3 placeholder:text-gray-700 placeholder:font-sans'
                    id=''
                    cols='45'
                    rows='5'
                  ></textarea>
                  <br />
                </div>
                <div className='btn text-center'>
                  <button
                    onClick={(e) => e.preventDefault()}
                    className='bg-blue-800 px-12 hover:bg-blue-700 cursor-pointer active:bg-blue-900 py-2 text-white rounded-lg'
                  >
                    Submit
                  </button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </section>
    </div>
  );
};

export default Contact;
